[package]
name = "aoc-2024"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.95"
good_lp = { version = "1.10.0", features = ["microlp"], default_features = false }
itertools = "0.13.0"
regex = "1.11.1"
